### ISSUE TITLE
TestHasIsBloomCached failures

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs-blockstore#6]
Moved from: https://github.com/ipfs/go-ipfs/issues/3208

```
--- FAIL: TestHasIsBloomCached (0.03s)
    bloom_cache_test.go:100: Bloom filter has cache miss rate of more than 5%
FAIL
FAIL    github.com/ipfs/go-ipfs/blocks/blockstore   0.053s
```

**Comment by taylormike** [comment]
I believe I found the root cause for this test failure. It appears to be a race condition/ timing issue that sometimes causes '```BloomActive()```'s' Goroutine to read ```b.active``` prior to ```b.active```'s assignment via '```Rebuild()```'s' Goroutine. 

I was able to consistently reproduce this test failure after adding a 300 Microsecond sleep in Rebuild.
(See code snippet below)

Thoughts? 

Rebuild's() Goroutine:
```Go	
        close(b.rebuildChan)
	time.Sleep(300 * time.Microsecond) //<-- Temp Code that reproduces the test failure
	atomic.StoreInt32(&b.active, 1)
```
BloomActive's() Goroutine:
```Go
func (b *bloomcache) BloomActive() bool {
	return atomic.LoadInt32(&b.active) != 0
}
```

**Comment by whyrusleeping** [comment]
@taylormike does it happen if you put that sleep specifically there? Or does it also work if you put the sleep before the channel close?

**Comment by taylormike** [comment]
@whyrusleeping 
1) The test fails if I put the sleep specifically there. (one sleep)
2) The test passes if I put the sleep before the channel close. (one sleep)
3) The test fails if I put the sleep there and I put the sleep before the channel close. (two sleeps)
